// Generated by gencpp from file moving_file/moving_stf.msg
// DO NOT EDIT!


#ifndef MOVING_FILE_MESSAGE_MOVING_STF_H
#define MOVING_FILE_MESSAGE_MOVING_STF_H

#include <ros/service_traits.h>


#include <moving_file/moving_stfRequest.h>
#include <moving_file/moving_stfResponse.h>


namespace moving_file
{

struct moving_stf
{

typedef moving_stfRequest Request;
typedef moving_stfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moving_stf
} // namespace moving_file


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moving_file::moving_stf > {
  static const char* value()
  {
    return "9b826a668338f1daad3bd62eab0c5bf8";
  }

  static const char* value(const ::moving_file::moving_stf&) { return value(); }
};

template<>
struct DataType< ::moving_file::moving_stf > {
  static const char* value()
  {
    return "moving_file/moving_stf";
  }

  static const char* value(const ::moving_file::moving_stf&) { return value(); }
};


// service_traits::MD5Sum< ::moving_file::moving_stfRequest> should match
// service_traits::MD5Sum< ::moving_file::moving_stf >
template<>
struct MD5Sum< ::moving_file::moving_stfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moving_file::moving_stf >::value();
  }
  static const char* value(const ::moving_file::moving_stfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moving_file::moving_stfRequest> should match
// service_traits::DataType< ::moving_file::moving_stf >
template<>
struct DataType< ::moving_file::moving_stfRequest>
{
  static const char* value()
  {
    return DataType< ::moving_file::moving_stf >::value();
  }
  static const char* value(const ::moving_file::moving_stfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moving_file::moving_stfResponse> should match
// service_traits::MD5Sum< ::moving_file::moving_stf >
template<>
struct MD5Sum< ::moving_file::moving_stfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moving_file::moving_stf >::value();
  }
  static const char* value(const ::moving_file::moving_stfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moving_file::moving_stfResponse> should match
// service_traits::DataType< ::moving_file::moving_stf >
template<>
struct DataType< ::moving_file::moving_stfResponse>
{
  static const char* value()
  {
    return DataType< ::moving_file::moving_stf >::value();
  }
  static const char* value(const ::moving_file::moving_stfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVING_FILE_MESSAGE_MOVING_STF_H
