// Generated by gencpp from file moving_file/moving_stfResponse.msg
// DO NOT EDIT!


#ifndef MOVING_FILE_MESSAGE_MOVING_STFRESPONSE_H
#define MOVING_FILE_MESSAGE_MOVING_STFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moving_file
{
template <class ContainerAllocator>
struct moving_stfResponse_
{
  typedef moving_stfResponse_<ContainerAllocator> Type;

  moving_stfResponse_()
    : c()  {
    }
  moving_stfResponse_(const ContainerAllocator& _alloc)
    : c(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::moving_file::moving_stfResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moving_file::moving_stfResponse_<ContainerAllocator> const> ConstPtr;

}; // struct moving_stfResponse_

typedef ::moving_file::moving_stfResponse_<std::allocator<void> > moving_stfResponse;

typedef boost::shared_ptr< ::moving_file::moving_stfResponse > moving_stfResponsePtr;
typedef boost::shared_ptr< ::moving_file::moving_stfResponse const> moving_stfResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moving_file::moving_stfResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moving_file::moving_stfResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moving_file::moving_stfResponse_<ContainerAllocator1> & lhs, const ::moving_file::moving_stfResponse_<ContainerAllocator2> & rhs)
{
  return lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moving_file::moving_stfResponse_<ContainerAllocator1> & lhs, const ::moving_file::moving_stfResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moving_file

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::moving_file::moving_stfResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moving_file::moving_stfResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving_file::moving_stfResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving_file::moving_stfResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving_file::moving_stfResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving_file::moving_stfResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moving_file::moving_stfResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aebdefad0841fcaf183a94e2efaa1152";
  }

  static const char* value(const ::moving_file::moving_stfResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaebdefad0841fcafULL;
  static const uint64_t static_value2 = 0x183a94e2efaa1152ULL;
};

template<class ContainerAllocator>
struct DataType< ::moving_file::moving_stfResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moving_file/moving_stfResponse";
  }

  static const char* value(const ::moving_file::moving_stfResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moving_file::moving_stfResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string c\n"
"\n"
;
  }

  static const char* value(const ::moving_file::moving_stfResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moving_file::moving_stfResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moving_stfResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moving_file::moving_stfResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moving_file::moving_stfResponse_<ContainerAllocator>& v)
  {
    s << indent << "c: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVING_FILE_MESSAGE_MOVING_STFRESPONSE_H
