controller_manager_ns: controller_manager
controller_list:
  - name: metrology_robot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  - name: metrology_robot/turntable_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [turntable_revolve_joint]